### ISSUE TITLE
implant + check is failing if the iso content is too small

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/isomd5sum#18]
It can be seen on Fedora 27 when running the test:
https://github.com/rhinstaller/isomd5sum/blob/master/testpyisomd5sum.py
If I add 500K file to the working directory the test result is pass.

**Comment by squimrel** [comment]
Well, I don't know what to do about this. There's simply a test that requires the file to be N bytes large. We could reduce this but that doesn't fix anything.

Is there any special reason you need the test to pass for a custom iso?

**Comment by squimrel** [comment]
Rereading the title. I must add that the implant doesn't fail for me. You'll have to make sure that it doesn't contain an isomd5sum yet though, otherwise it'll correctly fail.

**Comment by bcl** [comment]
Running on F29 I don't see this error.

**Comment by hosni** [comment]
Hello,
Same Here!
For reproduce this, you can follow these steps:
Clone (not download) this repository, then run: `make` and `make test`, You see test is passed and It's Okay.
Then remove `.git` directory (to reduce amount of files) and run `make test` again, The test is Fail!

Also when I use `checkisomd5` command with verbose option, I saw `;FRAGMENT` that appends to the `Fragment sums` of the iso, In my tests, It only appends when amount of file is low!

![image](https://user-images.githubusercontent.com/47793698/126836877-44390166-1b78-45af-b378-f29f3432b97d.png)
