### ISSUE TITLE
Koji build fails on i686 and armv7hl

### ISSUE THREAD

**Issue by bcl** [rhinstaller/isomd5sum#4]
i686 log:
https://koji.fedoraproject.org/koji/taskinfo?taskID=19912455

arm log:
https://kojipkgs.fedoraproject.org//work/tasks/2480/19912480/build.log

So size_t on some arches isn't big enough.

**Comment by bcl** [comment]
@squimrel can you take a look at this? (apparently I can't directly assign the bug to you.)

**Comment by squimrel** [comment]
Uhh my bad I guess. I'm on it.

**Comment by squimrel** [comment]
I'm sorry. Thanks for the merge anyways.
